---
- hosts: all
  become: true
  tasks:
  vars:
    motd:
      - Ansible Manage Node by qabrevilla

  vars_prompt:

      - name: username
        prompt: input your user name
        private: false
      - name: uid
        prompt: Input your ownn UID
        private: false

  tasks:
  - name: Banner MOTD
    ansible.builtin.debug:
      msg:
        - "{{ motd }}"

  - name: install python3 and pip3 for Ubuntu
    apt:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install python3 and pip3 for CentOS
    package:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "centos"

  - name: install openjdk for Ubuntu
    apt:
      name:
        - openjdk -17 -jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install openjdk for CentOS
    yum:
      name:
        - java-11-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "centos"


  - name: Create a user
    ansible.builtin.user:
      name: "{{ username }}"
      comment: NewUser
      uid: "{{ uid }}"
      createhome: yes
      home: /home/"{{ username }}"
      shell: /bin/bash
